### ISSUE TITLE
Entity ID is too generic

### ISSUE THREAD

**Issue by firestrife23** [Amateur-God/home-assistant-technetiumdns#4]
To avoid aggravating new users trying to identify Entity ID created by the integration. See below for example

`sensor.update_available` to `sensor.technitium_update_available`

**Comment by Amateur-God** [comment]
thank you for this issue i didnt think of this 

> To avoid aggravating new users trying to identify Entity ID created by the integration. See below for example
> 
> `sensor.update_available` to `sensor.technitium_update_available`
